Build #46 - Fix JAXB error by changing Java from 17 to 8
- Change Java version from 17 to 8 to fix javax.xml.bind.annotation.XmlSchema error
- This resolves NoClassDefFoundError that occurs with Java 9+ due to JAXB removal
- Java 8 includes JAXB by default, which is required by Android SDK tools
- This should finally allow buildozer to access Android SDK tools properly